/**
 * Frontend mirror of the backend product DTOs
 * (backend/src/Kartly.Application/Products/ProductDtos.cs).
 */

/** The fixed set of product categories — mirrors backend ProductCategories.All. */
export const PRODUCT_CATEGORIES = [
  'Smartphones',
  'Laptops',
  'Audio',
  'Monitors',
  'Accessories',
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  category: string;
  brand: string | null;
  model: string | null;
  description: string | null;
  imageUrl: string | null;
  price: number;
  discountPrice: number | null;
  stockQuantity: number;
  warrantyMonths: number | null;
  isFeatured: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PagedResult<T> {
  items: T[];
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
}

export type ProductSortBy = 'CreatedAt' | 'Name' | 'Price';

export interface ProductQuery {
  search?: string;
  brand?: string;
  isFeatured?: boolean;
  isActive?: boolean;
  minPrice?: number;
  maxPrice?: number;
  sortBy?: ProductSortBy;
  sortDescending?: boolean;
  page?: number;
  pageSize?: number;
}

/** Create payload — slug/sku optional (auto-generated by the API when omitted). */
export interface CreateProductRequest {
  name: string;
  category: string;
  price: number;
  slug?: string;
  sku?: string;
  brand?: string | null;
  model?: string | null;
  description?: string | null;
  imageUrl?: string | null;
  discountPrice?: number | null;
  stockQuantity?: number;
  warrantyMonths?: number | null;
  isFeatured?: boolean;
  isActive?: boolean;
}

/** Update payload — full replace, so slug and sku are required. */
export interface UpdateProductRequest {
  name: string;
  slug: string;
  sku: string;
  category: string;
  price: number;
  brand?: string | null;
  model?: string | null;
  description?: string | null;
  imageUrl?: string | null;
  discountPrice?: number | null;
  stockQuantity?: number;
  warrantyMonths?: number | null;
  isFeatured?: boolean;
  isActive?: boolean;
}
